INSERT INTO TABLEA ( N,TXT,FIELDINT,FIELDDATE,FIELDBLOB)VALUES ('104','txt1','100','2015-04-21','blobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblob
blobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblob
blobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblob
blobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblob
blobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblob
blobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblob
blobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblob
blobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblob');
INSERT INTO TABLEA ( N,TXT,FIELDINT,FIELDDATE,FIELDBLOB)VALUES ('105','txt2','200','2015-04-21','blobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblob
blobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblob
blobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblob');
UPDATE TABLEA SET TXT ='txt11',FIELDINT ='1001',FIELDDATE ='2015-04-30',FIELDBLOB ='blobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblob
blobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblob
blobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblob
blobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblob
blobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblob
blobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblob
blobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblob
blobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblobblob' where N ='104' ;
